const express=require("express")
const {register,login,post,getAllPosts,getOwnPosts,getSinglePost,deletePost,updatePost,getCommets,addCommet,deleteCommet}=require("../controllers/controller.js")
const {upload}=require("../utils/util.js")
const router=express.Router()
router.post("/register",register)
router.post("/login",login)
router.post("/post",upload.single('image'),post)
router.get("/posts",getAllPosts)
router.get("/getpost/:id",getSinglePost)
router.get("/usersposts",getOwnPosts)
router.delete("/delete/:id",deletePost)
router.put("/update/:id",updatePost)
router.get("/getCommets/:id",getCommets)
router.post("/addCommet/:id",addCommet)
router.delete("/deleteCommet/:id",deleteCommet)
module.exports={router}